import NavBar from '@/app/components/NavBar'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ko">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50`}>
				<NavBar />

				<div className="flex min-h-screen items-center justify-center font-sans">
					<div className="w-full max-w-4xl min-h-screen">
						<div className="flex flex-col gap-10">{children}</div>
					</div>
				</div>
			</body>
		</html>
	)
}
